spring:
  datasource: 
    url: jdbc:mysql://umc-study-db.c0hzdpwmekoh.ap-northeast-2.rds.amazonaws.com:3306/mteam
    username: admin
    password: adfw4278
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

cloud:
  aws:
    s3:
      bucket: umc-hackerton
    credentials:
      access-key: AKIAZHNUXZ4BVAMP3QJZ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false